import type { LearningResume, MockExamMode, MockExamResult, MockExamResume, UserData } from "@/domain/models";
import { defaultGame } from "@/lib/game-engine";
const DB_NAME="cosmo-quest"; const DB_VERSION=3; const STORE="app-state"; const CONTENT_STORE="content-overrides"; const KEY="current-user";
export const SAVE_VERSION=1;
export const defaultUser: UserData = { schemaVersion:6,saveVersion:SAVE_VERSION, player:{name:"ルナ",createdAt:new Date().toISOString(),lastActiveAt:new Date().toISOString()}, progress:{completedStageIds:[],readLessonIds:[],galleryIds:[],favoriteGalleryIds:[],currentStageId:"earth",xp:50,stageScores:{},stageStars:{},stages:{}}, statistics:{answered:0,correct:0,learningSeconds:0,streak:1,lastStudyDate:""}, settings:{theme:"dark",bgm:true,se:true,fontScale:"medium",vibration:false,reducedMotion:false,notifications:false}, achievements:[],questionHistory:[],learningHistory:[],reviews:[],topicProgress:{},game:defaultGame };
function open():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE);if(!db.objectStoreNames.contains(CONTENT_STORE))db.createObjectStore(CONTENT_STORE)};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
export async function loadUser():Promise<UserData>{try{const db=await open();return await new Promise(resolve=>{const req=db.transaction(STORE).objectStore(STORE).get(KEY);req.onsuccess=()=>resolve(req.result?migrate(req.result):structuredClone(defaultUser));req.onerror=()=>resolve(structuredClone(defaultUser))})}catch{return structuredClone(defaultUser)}}
export async function saveUser(user:UserData){try{const db=await open();return await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put({...user,saveVersion:SAVE_VERSION,player:{...user.player,lastActiveAt:new Date().toISOString()}},KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}catch{return}}
const RESUME_KEY="learning-resume";
export async function loadLearningResume():Promise<LearningResume|null>{try{const db=await open();return await new Promise(resolve=>{const req=db.transaction(STORE).objectStore(STORE).get(RESUME_KEY);req.onsuccess=()=>resolve(req.result??null);req.onerror=()=>resolve(null)})}catch{return null}}
export async function saveLearningResume(value:LearningResume){try{const db=await open();return await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(value,RESUME_KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}catch{return}}
export async function clearLearningResume(){try{const db=await open();return await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).delete(RESUME_KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}catch{return}}
const mockResumeKey=(rankId:MockExamResume["rankId"])=>`mock-exam-resume-${rankId}`;
export async function loadMockExamResume(rankId:MockExamResume["rankId"]):Promise<MockExamResume|null>{try{const db=await open();return await new Promise(resolve=>{const req=db.transaction(STORE).objectStore(STORE).get(mockResumeKey(rankId));req.onsuccess=()=>resolve(req.result??null);req.onerror=()=>resolve(null)})}catch{return null}}
export async function saveMockExamResume(value:MockExamResume){try{const db=await open();return await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(value,mockResumeKey(value.rankId));tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}catch{return}}
export async function clearMockExamResume(rankId:MockExamResume["rankId"]){try{const db=await open();return await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).delete(mockResumeKey(rankId));tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}catch{return}}
const mockResultKey=(rankId:MockExamResume["rankId"],mode:MockExamMode)=>`mock-exam-result-${rankId}-${mode}`;
export async function loadMockExamResult(rankId:MockExamResume["rankId"],mode:MockExamMode):Promise<MockExamResult|null>{try{const db=await open();return await new Promise(resolve=>{const req=db.transaction(STORE).objectStore(STORE).get(mockResultKey(rankId,mode));req.onsuccess=()=>resolve(req.result??null);req.onerror=()=>resolve(null)})}catch{return null}}
export async function saveMockExamResult(value:MockExamResult){try{const db=await open();return await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(value,mockResultKey(value.rankId,value.mode));tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}catch{return}}
export async function loadContentOverride<T>():Promise<T|null>{try{const db=await open();return await new Promise(resolve=>{const req=db.transaction(CONTENT_STORE).objectStore(CONTENT_STORE).get("catalog");req.onsuccess=()=>resolve(req.result??null);req.onerror=()=>resolve(null)})}catch{return null}}
export async function saveContentOverride<T>(catalog:T){try{const db=await open();return await new Promise<void>((resolve,reject)=>{const tx=db.transaction(CONTENT_STORE,"readwrite");tx.objectStore(CONTENT_STORE).put(catalog,"catalog");tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}catch{return}}
export async function clearAllData(){const db=await open();await Promise.all([STORE,CONTENT_STORE].map(name=>new Promise<void>((resolve,reject)=>{const tx=db.transaction(name,"readwrite");tx.objectStore(name).clear();tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})))}
type StoredUser=Partial<UserData>&{saveVersion?:number};
const migrations:Record<number,(value:StoredUser)=>StoredUser>={
  1:value=>({...value,saveVersion:1}),
};
function migrate(input:unknown):UserData{
  if(!input||typeof input!=="object")return structuredClone(defaultUser);
  let value={...(input as StoredUser)};
  let version=Number.isFinite(value.saveVersion)?Number(value.saveVersion):0;
  while(version<SAVE_VERSION){const next=version+1;value=migrations[next]?.(value)??{...value,saveVersion:next};version=next}
  const progress:Partial<UserData["progress"]>=value.progress??{};const game:UserData["game"]={...defaultGame,...value.game};
  return {...defaultUser,...value,schemaVersion:6,saveVersion:SAVE_VERSION,player:{...defaultUser.player,...value.player},progress:{...defaultUser.progress,...progress,completedStageIds:Array.isArray(progress.completedStageIds)?progress.completedStageIds:[],readLessonIds:Array.isArray(progress.readLessonIds)?progress.readLessonIds:[],galleryIds:Array.isArray(progress.galleryIds)?progress.galleryIds:[],favoriteGalleryIds:Array.isArray(progress.favoriteGalleryIds)?progress.favoriteGalleryIds:[],stageScores:progress.stageScores??{},stageStars:progress.stageStars??{},stages:progress.stages??{}},statistics:{...defaultUser.statistics,...value.statistics},settings:{...defaultUser.settings,...value.settings},game:{...defaultGame,...game,coins:Number.isFinite(game.coins)?game.coins:defaultGame.coins,unlockedShipIds:Array.isArray(game.unlockedShipIds)?game.unlockedShipIds:["capsule"],artifactIds:Array.isArray(game.artifactIds)?game.artifactIds:[],ownedItemIds:Array.isArray(game.ownedItemIds)?game.ownedItemIds:[],claimedDailyIds:Array.isArray(game.claimedDailyIds)?game.claimedDailyIds:[],claimedWeeklyIds:Array.isArray(game.claimedWeeklyIds)?game.claimedWeeklyIds:[]},achievements:Array.isArray(value.achievements)?value.achievements:[],questionHistory:Array.isArray(value.questionHistory)?value.questionHistory:[],learningHistory:Array.isArray(value.learningHistory)?value.learningHistory:[],reviews:Array.isArray(value.reviews)?value.reviews.map(r=>({...r,intervalDays:r.intervalDays??1,ease:r.ease??0})):[],topicProgress:value.topicProgress&&typeof value.topicProgress==="object"?value.topicProgress:{}};
}
