/* eslint-disable @typescript-eslint/no-explicit-any, jsx-a11y/click-events-have-key-events, jsx-a11y/no-static-element-interactions */
"use client";
import { useRef,useState } from "react";
import { RubyText as R } from "@/components/RubyText";
import type { ContentCatalog,GalleryItem,Question,Topic } from "@/domain/models";
type Mode="topics"|"questions"|"gallery"|"images"|"review"|"packs"|"export";
const date=()=>new Date().toISOString().slice(0,10),id=(p:string,i=0)=>`${p}-${Date.now()}-${i}`;
const download=(name:string,value:unknown)=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:"application/json"}));a.download=name;a.click();URL.revokeObjectURL(a.href)};
const rows=(text:string)=>{const lines=text.trim().split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const d=lines[0].includes("\t")?"\t":",";const split=(x:string)=>x.split(d).map(v=>v.trim().replace(/^"|"$/g,""));const h=split(lines[0]);return lines.slice(1).map(x=>Object.fromEntries(split(x).map((v,i)=>[h[i]??`c${i}`,v])))};
export function BulkProduction({catalog,commit}:{catalog:ContentCatalog;commit:(p:Partial<ContentCatalog>,m?:string)=>void}){const[mode,setMode]=useState<Mode>("topics"),[pack,setPack]=useState("Pack001"),[topic,setTopic]=useState(catalog.topics[0]?.id??""),[text,setText]=useState(""),[query,setQuery]=useState(""),[rank,setRank]=useState("all"),[chapter,setChapter]=useState("all"),[image,setImage]=useState("all"),[count,setCount]=useState("all");const file=useRef<HTMLInputElement>(null);
 const addTopics=(data:any[])=>{const now=date();const ts:Topic[]=data.map((r,i)=>{const key=r.id||id("topic",i);return{id:key,title:r.title||r.タイトル||`Topic ${i+1}`,category:r.category||r.カテゴリ||"未分類(みぶんるい)",description:r.description||r.本文||"",importance:Number(r.importance||1) as Topic["importance"],difficulty:Number(r.difficulty||1) as Topic["difficulty"],grades:[Number(r.grade||r.ランク||4) as 4],prerequisiteTopicIds:String(r.prerequisite||"").split("|").filter(Boolean),relatedTopicIds:[],galleryId:`gallery-${key}`,imageIds:[],diagramIds:[],triviaIds:[],questionIds:[],animationIds:[],order:catalog.topics.length+i+1,packId:pack,chapterId:r.chapterId||r.章||"",areaId:r.areaId||r.エリア||"",tags:String(r.tags||r.タグ||"").split("|").filter(Boolean),createdAt:now,updatedAt:now}});const gs:GalleryItem[]=ts.map(t=>({id:t.galleryId!,title:t.title,subtitle:"",category:t.category,icon:"✦",description:t.description,facts:[],relatedIds:[],tags:[`pack:${pack}`],packId:pack,createdAt:now,relatedTopicIds:[t.id]}));commit({topics:[...catalog.topics,...ts],gallery:[...catalog.gallery,...gs]},`${ts.length}件(けん)を一括追加(いっかつついか)しました`);setText("")};
 const read=async(f?:File)=>{if(!f)return;if(/\.xlsx?$/i.test(f.name)){const XLSX=await import("xlsx");const b=XLSX.read(await f.arrayBuffer());addTopics(XLSX.utils.sheet_to_json(b.Sheets[b.SheetNames[0]]))}else addTopics(rows(await f.text()))};
 const addQuestions=()=>{const data=rows(text);const fallback=text.trim().split(/\n\s*\n/).map(b=>{const x=b.split(/\r?\n/);return{prompt:x[0],option1:x[1],option2:x[2],option3:x[3],option4:x[4],correct:x[5],reason:x[6]}});const source=data.length?data:fallback,t=catalog.topics.find(x=>x.id===topic);const qs:Question[]=source.slice(0,20).filter((r:any)=>r.prompt).map((r:any,i)=>({id:id("question",i),stageId:"earth",topicId:topic,type:(r.type||"multiple-choice") as Question["type"],grade:t?.grades[0]===3?3:t?.grades[0]===5?5:4,difficulty:Number(r.difficulty||1) as Question["difficulty"],category:t?.category??"",tags:[`pack:${pack}`],prompt:r.prompt,options:[r.option1,r.option2,r.option3,r.option4].filter(Boolean),correct:Number(r.correct||0),explanation:{conclusion:r.conclusion||"",reason:r.reason||"",memoryTip:r.memoryTip||"",examPoint:r.examPoint||"",trivia:r.trivia||""}}));commit({questions:[...catalog.questions,...qs],topics:catalog.topics.map(x=>x.id===topic?{...x,questionIds:[...x.questionIds,...qs.map(q=>q.id)],updatedAt:date()}:x)},`${qs.length}問(もん)を登録(とうろく)しました`);setText("")};
 const missing=catalog.topics.filter(t=>!t.imageIds.length&&!t.diagramIds.length),unfinished=catalog.topics.filter(t=>!t.description||catalog.questions.filter(q=>q.topicId===t.id).length<3||!t.imageIds.length);const packs=Array.from(new Set(["Pack001","Pack002",...catalog.topics.map(t=>t.packId).filter(Boolean) as string[]]));const data=(p:string)=>({packId:p,topics:catalog.topics.filter(t=>t.packId===p),questions:catalog.questions.filter(q=>q.tags.includes(`pack:${p}`)),gallery:catalog.gallery.filter(g=>g.packId===p),imagePrompts:catalog.imagePrompts.filter(x=>catalog.topics.some(t=>t.packId===p&&x.topicIds.includes(t.id)))});const filtered=catalog.topics.filter(t=>{const n=catalog.questions.filter(q=>q.topicId===t.id).length;return(!query||JSON.stringify(t).toLowerCase().includes(query.toLowerCase()))&&(rank==="all"||String(t.grades[0])===rank)&&(chapter==="all"||t.chapterId===chapter)&&(image==="all"||(image==="yes"?t.imageIds.length>0:!t.imageIds.length))&&(count==="all"||(count==="low"?n<3:n>=3))});
 return <section className="bulk-production"><header><div><small>HIGH-SPEED PRODUCTION</small><R as="h2" text="一括制作(いっかつせいさく)センター"/></div><label>ACTIVE PACK<select value={pack} onChange={e=>setPack(e.target.value)}>{packs.map(x=><option key={x}>{x}</option>)}</select></label></header><nav>{(["topics","questions","gallery","images","review","packs","export"] as Mode[]).map(x=><button className={mode===x?"active":""} onClick={()=>setMode(x)} key={x}>{x}</button>)}</nav><div className="work-stats"><span><R text="今日追加(きょうついか) Topic"/><b>{catalog.topics.filter(t=>t.createdAt===date()).length}</b></span><span><R text="Pack問題数(もんだいすう)"/><b>{catalog.questions.filter(q=>q.tags.includes(`pack:${pack}`)).length}</b></span><span><R text="Pack図鑑数(ずかんすう)"/><b>{catalog.gallery.filter(g=>g.packId===pack).length}</b></span></div>
 {mode==="topics"&&<div className="bulk-layout"><article className="bulk-card"><R as="h3" text="CSV・Excel一括追加(いっかつついか)"/><div className="drop-zone" onClick={()=>file.current?.click()}>⇧<R as="strong" text="ファイルを選択(せんたく)"/><small>.csv / .xlsx / .xls</small></div><input hidden ref={file} type="file" accept=".csv,.xlsx,.xls" onChange={e=>read(e.target.files?.[0])}/></article><article className="bulk-card"><R as="h3" text="表(ひょう)をコピー＆貼(は)り付(つ)け"/><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={'title\tdescription\tcategory\tgrade\tchapterId\ttags\n地球(ちきゅう)\t本文...\t惑星\t4\tchapter-1\t基礎|重要'}/><button onClick={()=>addTopics(rows(text))}>一括登録(いっかつとうろく)</button></article></div>}
 {mode==="questions"&&<article className="bulk-card"><label>対象Topic<select value={topic} onChange={e=>setTopic(e.target.value)}>{catalog.topics.map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select></label><R as="h3" text="最大(さいだい)20問(もん)を貼(は)り付(つ)け"/><textarea rows={17} value={text} onChange={e=>setText(e.target.value)} placeholder={'prompt,option1,option2,option3,option4,correct,reason\n問題文,A,B,C,D,0,理由'}/><button onClick={addQuestions}>問題(もんだい)を一括登録(いっかつとうろく)</button></article>}
 {mode==="gallery"&&<div className="bulk-table"><header><span>Topic</span><span>説明(せつめい)</span><span>比較(ひかく)・雑学(ざつがく)</span></header>{catalog.gallery.slice(0,200).map(g=><article key={g.id}><R as="strong" text={g.title}/><textarea value={g.description} onChange={e=>commit({gallery:catalog.gallery.map(x=>x.id===g.id?{...x,description:e.target.value}:x)})}/><textarea value={g.comparison??""} onChange={e=>commit({gallery:catalog.gallery.map(x=>x.id===g.id?{...x,comparison:e.target.value}:x)})}/></article>)}</div>}
 {mode==="images"&&<><div className="bulk-toolbar"><R as="strong" text={`画像未作成(がぞうみさくせい)：${missing.length} Topic`}/><button onClick={()=>navigator.clipboard.writeText(missing.map(t=>`【${t.id}】${t.title}\n教育用宇宙図鑑イラスト。背景白、文字なし、科学的に正確。`).join("\n\n"))}>全(ぜん)プロンプトをコピー</button></div><div className="prompt-list">{missing.map(t=><article key={t.id}><div><small>{t.id}</small><R as="strong" text={t.title}/></div><button onClick={()=>navigator.clipboard.writeText(`Topic「${t.title}」の教育用宇宙図鑑イラスト。背景白、文字なし、科学的に正確。`)}>コピー</button></article>)}</div></>}
 {mode==="review"&&<><div className="bulk-toolbar"><R as="strong" text={`未完成(みかんせい)：${unfinished.length} Topic`}/><button onClick={()=>commit({topics:catalog.topics.map(t=>unfinished.includes(t)?{...t,tags:Array.from(new Set([...(t.tags??[]),"reviewed"])),updatedAt:date()}:t)},"一括承認(いっかつしょうにん)しました")}>表示中(ひょうじちゅう)を一括承認(いっかつしょうにん)</button></div><div className="review-grid">{unfinished.map(t=>{const n=catalog.questions.filter(q=>q.topicId===t.id).length;return <article key={t.id}><input type="checkbox"/><div><R as="strong" text={t.title}/><small>{t.packId??"NO PACK"}</small></div><span className={!t.description?"bad":""}>本文</span><span className={n<3?"warn":""}>問題 {n}</span><span className={!t.imageIds.length?"info":""}>画像</span></article>})}</div></>}
 {mode==="packs"&&<div className="pack-grid">{packs.map(p=>{const d=data(p);return <article key={p}><small>CONTENT PACK</small><h3>{p}</h3><span>{d.topics.length} Topics</span><span>{d.questions.length} Questions</span><button onClick={()=>setPack(p)}>編集対象(へんしゅうたいしょう)にする</button></article>})}<button className="new-pack" onClick={()=>setPack(`Pack${String(packs.length+1).padStart(3,"0")}`)}>＋<R text="新規(しんき)Pack"/></button></div>}
 {mode==="export"&&<div className="pack-grid">{packs.map(p=><article key={p}><h3>{p}</h3><span>{data(p).topics.length} Topics</span><button onClick={()=>download(`${p}.json`,data(p))}>Pack JSON Export</button></article>)}<article><h3>ALL PACKS</h3><button onClick={()=>download("all-packs.json",catalog)}>一括(いっかつ)Export</button></article></div>}
 <section className="advanced-search"><header><R as="strong" text="高度検索(こうどけんさく)"/><b>{filtered.length} Topics</b></header><div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="タイトル・タグ検索"/><select value={rank} onChange={e=>setRank(e.target.value)}><option value="all">全ランク</option><option value="4">ベガ</option><option value="3">アルタイル</option><option value="2">シリウス</option><option value="1">ポラリス</option></select><select value={chapter} onChange={e=>setChapter(e.target.value)}><option value="all">全章</option>{catalog.chapters?.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select><select value={image} onChange={e=>setImage(e.target.value)}><option value="all">画像すべて</option><option value="yes">画像あり</option><option value="no">画像なし</option></select><select value={count} onChange={e=>setCount(e.target.value)}><option value="all">問題数すべて</option><option value="low">3問未満</option><option value="enough">3問以上</option></select></div></section></section>}
