"use client";
import { useRef, useState } from "react";
import type { ContentCatalog, Question, UserData } from "@/domain/models";
import { RubyText as R } from "@/components/RubyText";

type Tab="questions"|"gallery"|"stages"|"json"|"debug";
export function DeveloperConsole({catalog,onCatalog,user,onUser,onClose}:{catalog:ContentCatalog;onCatalog:(c:ContentCatalog)=>void;user:UserData;onUser:(u:UserData)=>void;onClose:()=>void}){
 const[tab,setTab]=useState<Tab>("questions");const[search,setSearch]=useState("");const file=useRef<HTMLInputElement>(null);
 const download=(name:string,value:unknown)=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:"application/json"}));a.download=name;a.click();URL.revokeObjectURL(a.href)};
 const importJson=(f?:File)=>{if(!f)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(String(reader.result));if(parsed.stages&&parsed.questions&&parsed.gallery)onCatalog(parsed);else alert("カタログ形式ではありません")}catch{alert("JSONを読み込めませんでした")}};reader.readAsText(f)};
 return <div className="developer-console"><header><div><small>PRIVATE TOOL</small><h1>Cosmo Quest Developer</h1></div><button onClick={onClose}>×</button></header><nav>{(["questions","gallery","stages","json","debug"] as Tab[]).map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav>
 {tab==="questions"&&<section><div className="dev-toolbar"><input placeholder="ID・本文・タグを検索" value={search} onChange={e=>setSearch(e.target.value)}/><button onClick={()=>{const q:Question={id:`question-${Date.now()}`,stageId:"earth",topicId:"new",type:"multiple-choice",grade:5,difficulty:1,category:"未分類",tags:[],prompt:"新(あたら)しい問題(もんだい)",options:["選択肢(せんたくし)1","選択肢(せんたくし)2"],correct:0,explanation:{conclusion:"正解(せいかい)です。",reason:"理由(りゆう)を入力(にゅうりょく)してください。",memoryTip:"覚(おぼ)え方(かた)",examPoint:"試験(しけん)ポイント",trivia:"豆知識(まめちしき)"}};onCatalog({...catalog,questions:[q,...catalog.questions]})}}>＋ 追加</button></div><div className="dev-list">{catalog.questions.filter(q=>JSON.stringify(q).toLowerCase().includes(search.toLowerCase())).map(q=><article key={q.id}><div><small>{q.id} ・ {q.type}</small><R as="strong" text={q.prompt}/><span>{q.tags.join(" / ")||"タグなし"}</span></div><select value={q.difficulty} onChange={e=>onCatalog({...catalog,questions:catalog.questions.map(x=>x.id===q.id?{...x,difficulty:Number(e.target.value) as Question["difficulty"]}:x)})}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select><button onClick={()=>onCatalog({...catalog,questions:[...catalog.questions,{...q,id:`${q.id}-copy-${Date.now()}`} ]})}>複製</button><button onClick={()=>{const tags=prompt("カンマ区切りのタグ",q.tags.join(","));if(tags!==null)onCatalog({...catalog,questions:catalog.questions.map(x=>x.id===q.id?{...x,tags:tags.split(",").map(v=>v.trim()).filter(Boolean)}:x)})}}>タグ</button><button className="danger" onClick={()=>confirm("削除しますか？")&&onCatalog({...catalog,questions:catalog.questions.filter(x=>x.id!==q.id)})}>削除</button></article>)}</div></section>}
 {tab==="gallery"&&<section><div className="dev-toolbar"><b>{catalog.gallery.length} entries</b><button onClick={()=>onCatalog({...catalog,gallery:[...catalog.gallery,{id:`gallery-${Date.now()}`,category:"未分類",title:"新規(しんき)項目(こうもく)",subtitle:"",icon:"✦",description:"",facts:[],relatedIds:[],tags:[]}]})}>＋ 追加</button></div><div className="dev-list">{catalog.gallery.map(g=><article key={g.id}><span className="dev-icon">{g.icon}</span><div><small>{g.id}</small><R as="strong" text={g.title}/><span>{g.category}</span></div><button onClick={()=>{const category=prompt("カテゴリ",g.category);if(category)onCatalog({...catalog,gallery:catalog.gallery.map(x=>x.id===g.id?{...x,category}:x)})}}>編集</button><button onClick={()=>onCatalog({...catalog,gallery:catalog.gallery.filter(x=>x.id!==g.id)})}>削除</button></article>)}</div></section>}
 {tab==="stages"&&<section><div className="dev-toolbar"><b>{catalog.stages.length} stages</b><button onClick={()=>onCatalog({...catalog,stages:[...catalog.stages,{id:`stage-${Date.now()}`,order:catalog.stages.length+1,name:"新規(しんき)ステージ",subtitle:"",category:"追加(ついか)カテゴリ",icon:"✦",color:"#79ddff",estimatedMinutes:10,xpReward:100,lessonIds:[],questionIds:[],galleryId:"",summary:"",basicData:[],prerequisiteStageIds:catalog.stages.length?[catalog.stages.at(-1)!.id]:[],requiredScore:70}]})}>＋ 追加</button></div><div className="dev-list">{[...catalog.stages].sort((a,b)=>a.order-b.order).map((s,i)=><article key={s.id}><span className="dev-icon">{s.icon}</span><div><small>{s.id}</small><R as="strong" text={s.name}/><span>順番 {s.order} ・ 前提 {s.prerequisiteStageIds?.join(",")||"なし"}</span></div><button disabled={i===0} onClick={()=>{const before=catalog.stages.find(x=>x.order===s.order-1);if(!before)return;onCatalog({...catalog,stages:catalog.stages.map(x=>x.id===s.id?{...x,order:x.order-1}:x.id===before.id?{...x,order:x.order+1}:x)})}}>↑</button><button onClick={()=>{const name=prompt("表示名（ふりがな記法対応）",s.name);if(name)onCatalog({...catalog,stages:catalog.stages.map(x=>x.id===s.id?{...x,name}:x)})}}>編集</button><button onClick={()=>{const lock=prompt("前提ステージID（空欄でロックなし）",s.prerequisiteStageIds?.join(",")||"");if(lock!==null)onCatalog({...catalog,stages:catalog.stages.map(x=>x.id===s.id?{...x,prerequisiteStageIds:lock.split(",").filter(Boolean)}:x)})}}>ロック</button><button className="danger" onClick={()=>confirm("削除しますか？")&&onCatalog({...catalog,stages:catalog.stages.filter(x=>x.id!==s.id)})}>削除</button></article>)}</div></section>}
 {tab==="json"&&<section className="dev-actions"><button onClick={()=>download("cosmo-quest-content.json",catalog)}>コンテンツをエクスポート</button><button onClick={()=>file.current?.click()}>JSONをインポート</button><input hidden ref={file} type="file" accept="application/json" onChange={e=>importJson(e.target.files?.[0])}/><button onClick={()=>download(`cosmo-quest-backup-${new Date().toISOString().slice(0,10)}.json`,{catalog,user})}>完全バックアップ</button><pre>{JSON.stringify({schemaVersion:catalog.schemaVersion,stages:catalog.stages.length,questions:catalog.questions.length,gallery:catalog.gallery.length},null,2)}</pre></section>}
 {tab==="debug"&&<section className="dev-actions"><button onClick={()=>onUser({...user,progress:{...user.progress,completedStageIds:catalog.stages.map(s=>s.id)}})}>全ステージ解放</button><button onClick={()=>onUser({...user,progress:{...user.progress,xp:user.progress.xp+1000}})}>経験値 ＋1000</button><button onClick={()=>onUser({...user,progress:{...user.progress,galleryIds:catalog.gallery.map(g=>g.id)}})}>図鑑全取得</button><button onClick={()=>onUser({...user,achievements:catalog.achievements.map(a=>a.id)})}>実績全解除</button><button className="danger" onClick={()=>confirm("進行をリセットしますか？")&&onUser({...user,progress:{...user.progress,completedStageIds:[],readLessonIds:[],galleryIds:[],favoriteGalleryIds:[],xp:0,stageScores:{},stageStars:{}},achievements:[],questionHistory:[],learningHistory:[],reviews:[]})}>進行リセット</button></section>}
 </div>
}
