/* eslint-disable @typescript-eslint/no-unused-vars, jsx-a11y/click-events-have-key-events, jsx-a11y/no-static-element-interactions */
"use client";

import { useEffect, useState } from "react";
import { achievements as achievementData, contentCatalog as baseCatalog, gallery, lessons, questions, stages } from "@/data/catalog";
import type { AnswerValue, AppSettings, ContentCatalog, LearningResume, Question, Stage, UserData } from "@/domain/models";
import { RubyText as R } from "@/components/RubyText";
import { earnedAchievements, galleryRate, getLevel, getShipRank, getStageStatus, getTitle } from "@/lib/progression";
import { clearLearningResume, defaultUser, loadContentOverride, loadLearningResume, loadUser, saveContentOverride, saveLearningResume, saveUser } from "@/lib/storage";
import { isAnswerCorrect, makeReview } from "@/lib/question-engine";
import { QuestionInput } from "@/features/questions/QuestionInput";
import { MockExam } from "@/features/mock/MockExam";
import { updateTopicProgress } from "@/lib/learning-engine";
import { TopicPath } from "@/features/topics/TopicPath";
import { StageMiniTest } from "@/features/stage/StageMiniTest";
import { GradeProgress, MapJourney, NextDestinationCard, StageStatusPanel } from "@/features/stage/StageStatusPanel";
import { canClearStage, emptyStageProgress, nextStage, starsForScore, updateMainProgress } from "@/lib/stage-engine";
import { ReleaseDashboard } from "@/features/release/ReleaseDashboard";
import { RankJourney } from "@/features/journey/RankJourney";
import { CosmoTree } from "@/features/journey/CosmoTree";
import { ContentStudio } from "@/features/developer/ContentStudio";
import { LearningNav, ReleaseCandidate } from "@/features/release/ReleaseCandidate";
import { AdventureHome, GalaxyMap } from "@/features/adventure/AdventureMode";
import { EducationalDiagram } from "@/components/EducationalDiagram";
import { SpaceRpg } from "@/features/adventure/SpaceRpg";
import { artifactFor } from "@/lib/game-engine";
import { PwaDiagnostics } from "@/components/PwaDiagnostics";
import { AppAudio, playAppSound } from "@/components/AppAudio";
import { HomeDashboard } from "@/features/home/HomeDashboard";

type View = "home"|"map"|"stage"|"lesson"|"quiz"|"explanation"|"mini-test"|"clear"|"library"|"gallery"|"rpg"|"profile"|"settings"|"mock"|"developer";

export function CosmoQuestApp() {
  const [user,setUser]=useState<UserData>(defaultUser); const [catalog,setCatalog]=useState<ContentCatalog>(baseCatalog); const [ready,setReady]=useState(false); const [view,setView]=useState<View>("home");
  const [stageId,setStageId]=useState("earth"); const [quizIndex,setQuizIndex]=useState(0); const [answer,setAnswer]=useState<AnswerValue|null>(null); const [isCorrect,setIsCorrect]=useState(false); const [toast,setToast]=useState(""); const [resume,setResume]=useState<LearningResume|null>(null); const [freeRouteAccess,setFreeRouteAccess]=useState(false);
  const stage=catalog.stages.find(s=>s.id===stageId)??catalog.stages[0]; const stageQuestions=catalog.questions.filter(q=>q.stageId===stage.id); const question=stageQuestions[quizIndex%Math.max(stageQuestions.length,1)];
  useEffect(()=>{Promise.all([loadUser(),loadContentOverride<ContentCatalog>(),loadLearningResume()]).then(([v,c,r])=>{setUser(v);setResume(r);const valid=c&&c.schemaVersion>=baseCatalog.schemaVersion&&Array.isArray(c.stages)&&Array.isArray(c.questions)&&Array.isArray(c.gallery);if(valid)setCatalog({...baseCatalog,...c,topics:Array.isArray(c.topics)?c.topics:baseCatalog.topics,explanations:Array.isArray(c.explanations)?c.explanations:baseCatalog.explanations,trivia:Array.isArray(c.trivia)?c.trivia:baseCatalog.trivia,imagePrompts:Array.isArray(c.imagePrompts)?c.imagePrompts:baseCatalog.imagePrompts});if(new URLSearchParams(location.search).get("developer")==="1")setView("developer");setReady(true)}).catch(()=>setReady(true))},[]);
  useEffect(()=>{if(ready)saveUser(user)},[user,ready]);
  useEffect(()=>{document.documentElement.dataset.font=user.settings.fontScale;document.documentElement.dataset.motion=user.settings.reducedMotion?"reduced":"full"},[user.settings]);
  useEffect(()=>{const state={view,stageId};if(history.state?.view!==view||history.state?.stageId!==stageId)history.pushState(state,"",location.href);const pop=(event:PopStateEvent)=>{const next=event.state as {view?:View;stageId?:string}|null;if(next?.stageId)setStageId(next.stageId);setView(next?.view??"home")};addEventListener("popstate",pop);return()=>removeEventListener("popstate",pop)},[view,stageId]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),2400);return()=>clearTimeout(t)},[toast]);
  const level=getLevel(user.progress.xp); const back=()=>setView(view==="stage"?"map":["lesson","quiz","mini-test"].includes(view)?"stage":view==="gallery"?"library":"home");
  function openStage(id:string){setFreeRouteAccess(false);setStageId(id);setView("stage")}
  function openRankStage(id:string){setFreeRouteAccess(true);setStageId(id);setView("stage")}
  function begin(){clearLearningResume();setResume(null);setQuizIndex(0);setAnswer(null);setView("lesson")}
  function pauseLearning(){const saved:LearningResume={stageId:stage.id,quizIndex,view:view==="explanation"?"explanation":"quiz",answer,isCorrect,savedAt:new Date().toISOString()};saveLearningResume(saved);setResume(saved);setToast("学習(がくしゅう)の続(つづ)きを保存(ほぞん)しました");setView("home")}
  function resumeLearning(){if(!resume)return;setStageId(resume.stageId);setQuizIndex(resume.quizIndex);setAnswer(resume.answer);setIsCorrect(resume.isCorrect);setView(resume.view)}
  function startToday(){if(resume){resumeLearning();return}const current=catalog.stages.find(s=>s.id===user.progress.currentStageId)??catalog.stages[0];setStageId(current.id);setQuizIndex(0);setAnswer(null);setIsCorrect(false);clearLearningResume();setView("lesson")}
  function recordAnswer(q:Question,ok:boolean,stageRun=false){setUser(prev=>{const answered=prev.statistics.answered+1;const correct=prev.statistics.correct+(ok?1:0);const review=makeReview(q.id,ok);const stageProgress=stageRun?updateMainProgress(prev.progress.stages[stage.id],q.id,ok,stageQuestions.length):prev.progress.stages[stage.id];const next={...prev,progress:{...prev.progress,xp:prev.progress.xp+(ok?20:0),...(stageRun?{stages:{...prev.progress.stages,[stage.id]:stageProgress}}:{})},game:{...prev.game,coins:prev.game.coins+(ok?5:0)},statistics:{...prev.statistics,answered,correct},questionHistory:[...prev.questionHistory,{questionId:q.id,correct:ok,answeredAt:new Date().toISOString(),elapsedSeconds:12}],reviews:[...prev.reviews.filter(r=>r.questionId!==q.id),review],topicProgress:{...prev.topicProgress,[q.topicId]:updateTopicProgress(prev.topicProgress[q.topicId],ok,12)}};return{...next,achievements:Array.from(new Set([...next.achievements,...earnedAchievements(next)]))}})}
  function submit(q:Question,response:AnswerValue){if(answer!==null)return;setAnswer(response);const ok=isAnswerCorrect(q,response);setIsCorrect(ok);playAppSound(ok?"correct":"wrong");recordAnswer(q,ok,true)}
  function continueQuiz(){setView("explanation")}
  function nextQuestion(){if(quizIndex<stageQuestions.length-1){setQuizIndex(v=>v+1);setAnswer(null);setView("quiz")}else{clearLearningResume();setResume(null);setAnswer(null);setView("mini-test")}}
  function clearStage(miniScore:number){setUser(prev=>{const current={...(prev.progress.stages[stage.id]??emptyStageProgress),miniTestPassed:miniScore>=80,miniTestScore:miniScore};if(!canClearStage(current))return prev;const first=!prev.progress.completedStageIds.includes(stage.id),galleryFirst=!prev.progress.galleryIds.includes(stage.galleryId);const completed=Array.from(new Set([...prev.progress.completedStageIds,stage.id])),collected=Array.from(new Set([...prev.progress.galleryIds,stage.galleryId]));const next=nextStage(stage,catalog.stages),stars=starsForScore(current.mainScore,miniScore),bonus=(first?100:0)+(galleryFirst?30:0)+(current.mainScore===100?50:0),artifact=first?artifactFor(stage.id,prev.game.artifactIds):undefined;const updated={...prev,progress:{...prev.progress,completedStageIds:completed,galleryIds:collected,xp:prev.progress.xp+bonus,currentStageId:next?.id??stage.id,stageScores:{...prev.progress.stageScores,[stage.id]:current.mainScore},stageStars:{...prev.progress.stageStars,[stage.id]:stars},stages:{...prev.progress.stages,[stage.id]:{...current,completedAt:new Date().toISOString()}}},game:{...prev.game,coins:prev.game.coins+(first?100:20),artifactIds:artifact?[...prev.game.artifactIds,artifact.id]:prev.game.artifactIds,lastReward:artifact?{kind:"artifact" as const,label:`${artifact.name} を発見`,rarity:artifact.rarity}:{kind:"xp" as const,label:`STAGE CLEAR +${bonus} XP`}},statistics:{...prev.statistics,learningSeconds:prev.statistics.learningSeconds+stage.estimatedMinutes*60}};return{...updated,achievements:Array.from(new Set([...updated.achievements,...earnedAchievements(updated)]))}});playAppSound("reward");setToast("STAGE CLEAR · 報酬を獲得");setView("clear")}
  function updateSetting<K extends keyof AppSettings>(key:K,value:AppSettings[K]){setUser(v=>({...v,settings:{...v.settings,[key]:value}}))}
  if(!ready)return <Loading/>;
  const titles:Record<View,string>={home:"ホーム",map:"宇宙(うちゅう)マップ",stage:"天体(てんたい)情報(じょうほう)",lesson:"学習(がくしゅう)",quiz:"確認(かくにん)問題(もんだい)",explanation:"詳(くわ)しい解説(かいせつ)","mini-test":"ミニテスト",clear:"クリア",library:"宇宙(うちゅう)図鑑(ずかん)",gallery:"図鑑(ずかん)詳細(しょうさい)",rpg:"宇宙船(うちゅうせん)・基地(きち)",profile:"学習(がくしゅう)記録(きろく)",settings:"設定(せってい)",mock:"級別(きゅうべつ)模試(もし)",developer:"開発者(かいはつしゃ)モード"};
  if(view==="developer")return <ContentStudio catalog={catalog} onCatalog={c=>{setCatalog(c);saveContentOverride(c)}} user={user} onUser={setUser} onClose={()=>{history.replaceState(null,"",location.pathname);setView("home")}}/>;
  return <main className="app-shell"><div className="ambient" aria-hidden="true"><i/><i/><i/><i/></div>
    <AppAudio settings={user.settings}/><Header home={view==="home"} title={titles[view]} back={back} streak={user.statistics.streak} settings={()=>setView("settings")}/>{view!=="home"&&view!=="rpg"&&<LearningNav stage={catalog.stages.find(s=>s.id===user.progress.currentStageId)??stage} view={view} resume={()=>openStage(user.progress.currentStageId)}/>}
    <section className="content screen-enter">
      {view==="home"&&<HomeDashboard user={user} stages={catalog.stages} gallery={catalog.gallery} resume={resume} onContinue={startToday} onLibrary={()=>setView("library")} onRecords={()=>setView("profile")} onHangar={()=>setView("rpg")}/>}
      {view==="map"&&<><MapJourney current={catalog.stages.find(s=>s.id===user.progress.currentStageId)??catalog.stages[0]} next={catalog.stages.find(s=>s.order===(catalog.stages.find(x=>x.id===user.progress.currentStageId)?.order??0)+1)} completed={user.progress.completedStageIds.length} total={catalog.stages.length}/><GalaxyMap user={user} stages={catalog.stages} open={openStage}/><Map user={user} stagesList={catalog.stages} open={openStage}/><TopicPath topics={catalog.topics} user={user}/></>} 
      {view==="stage"&&<><StageDetail stage={stage} status={freeRouteAccess?"available":getStageStatus(stage.id,user,catalog.stages)} begin={begin}/><StageStatusPanel stage={stage} status={freeRouteAccess?"available":getStageStatus(stage.id,user,catalog.stages)} user={user} totalQuestions={stageQuestions.length}/></>} 
      {view==="lesson"&&<LessonScreen stage={stage} user={user} complete={()=>{const lesson=catalog.lessons.find(l=>l.stageId===stage.id);if(lesson)setUser(v=>({...v,progress:{...v.progress,readLessonIds:Array.from(new Set([...v.progress.readLessonIds,lesson.id])),stages:{...v.progress.stages,[stage.id]:{...(v.progress.stages[stage.id]??emptyStageProgress),lessonRead:true}}},learningHistory:[...v.learningHistory,{lessonId:lesson.id,completedAt:new Date().toISOString(),elapsedSeconds:stage.estimatedMinutes*60}]}));setView("quiz")}}/>}
      {view==="quiz"&&question&&<QuestionScreen question={question} index={quizIndex} total={stageQuestions.length} selected={answer} correct={isCorrect} submit={i=>submit(question,i)} next={continueQuiz} pause={pauseLearning}/>} 
      {view==="explanation"&&question&&<Explanation question={(()=>{const e=catalog.explanations.find(x=>x.id===(question.explanationId??`exp-${question.id}`));return e?{...question,explanation:{conclusion:e.conclusion,reason:e.reason,memoryTip:e.memoryTip,examPoint:e.examPoint,trivia:catalog.trivia.filter(t=>e.triviaIds.includes(t.id)).map(t=>t.body).join(" ")||question.explanation.trivia,otherChoices:e.otherChoices}}:question})()} correct={isCorrect} next={nextQuestion} pause={pauseLearning}/>} 
      {view==="mini-test"&&<StageMiniTest stage={stage} questions={stageQuestions} mainScore={user.progress.stages[stage.id]?.mainScore??0} onPass={clearStage} onRetryMain={()=>{setQuizIndex(0);setAnswer(null);setView("quiz")}}/>} 
      {view==="clear"&&<><Clear stage={stage} level={getLevel(user.progress.xp)} map={()=>setView("map")} library={()=>setView("library")}/><NextDestinationCard stage={nextStage(stage,catalog.stages)} depart={id=>{setStageId(id);setView("stage")}}/></>} 
      {view==="library"&&<Library user={user} open={id=>{setStageId(id);setView("gallery")}} toggleFavorite={id=>setUser(v=>({...v,progress:{...v.progress,favoriteGalleryIds:v.progress.favoriteGalleryIds.includes(id)?v.progress.favoriteGalleryIds.filter(x=>x!==id):[...v.progress.favoriteGalleryIds,id]}}))}/>} 
      {view==="gallery"&&<GalleryDetail stage={stage} unlocked={user.progress.galleryIds.includes(stage.id)} learn={()=>{setView("stage")}}/>}
      {view==="rpg"&&<div className="rpg-shell dedicated"><SpaceRpg user={user} gallery={catalog.gallery} onUser={setUser}/></div>}
      {view==="profile"&&<><Profile user={user}/><GradeProgress questions={catalog.questions} user={user}/></>} 
      {view==="settings"&&<Settings user={user} update={updateSetting}/>}
      {view==="mock"&&<MockExam questions={catalog.questions} onAnswer={(q,_a,ok)=>recordAnswer(q,ok)}/>} 
    </section>
    <Bottom view={view} go={setView}/>{toast&&<div className="toast" role="status">{toast}</div>}
  </main>
}

function Header({home,title,back,streak,settings}:{home:boolean;title:string;back:()=>void;streak:number;settings:()=>void}){return <header className="topbar">{home?<div className="brand-mark">CQ</div>:<button className="icon-btn" onClick={back} aria-label="もどる">←</button>}<div className="heading"><small>{home?"COSMO QUEST":"MISSION LOG"}</small><R as="strong" text={title}/></div>{home?<button className="streak"><span>🔥</span><b>{streak}</b></button>:<button className="icon-btn" onClick={settings} aria-label="せってい">⚙</button>}</header>}
function Bottom({view,go}:{view:View;go:(v:View)=>void}){return <nav className="bottom-nav phase4" aria-label="メインメニュー"><Nav active={view==="home"} icon="⌂" label="ホーム" click={()=>go("home")}/><Nav active={["map","stage","lesson","quiz","explanation","mini-test","clear"].includes(view)} icon="✦" label="航路(こうろ)" click={()=>go("map")}/><Nav active={view==="mock"} icon="◇" label="模試(もし)" click={()=>go("mock")}/><Nav active={["library","gallery","rpg"].includes(view)} icon="▤" label="図鑑(ずかん)" click={()=>go("library")}/><Nav active={view==="profile"} icon="◉" label="記録(きろく)" click={()=>go("profile")}/></nav>}
function Nav({active,icon,label,click}:{active:boolean;icon:string;label:string;click:()=>void}){return <button className={active?"active":""} onClick={click}><span>{icon}</span><R as="small" text={label}/></button>}
function Loading(){return <main className="app-shell loading"><div className="loader-orbit"><i/></div><strong>COSMO QUEST</strong><R text="航路(こうろ)を計算中(けいさんちゅう)…"/></main>}

function Home({user,level,goMap,goLibrary}:{user:UserData;level:number;goMap:()=>void;goLibrary:()=>void}){const next=stages.find(s=>getStageStatus(s.id,user)==="available")??stages[0];return <div className="home-view"><section className="hero-card"><div className="eyebrow"><span/> NEXT MISSION</div><R as="h1" text={`おかえり、${user.player.name}船長(せんちょう)。`}/><R as="p" text="今日(きょう)も宇宙(うちゅう)の謎(なぞ)をひとつ、解(と)き明(あ)かそう。"/><div className="planet-orbit"><div className="earth"><span/></div><i className="moon"/></div><button className="primary" onClick={goMap}><R text={`${next.name}へ向(む)かう`}/><b>→</b></button></section><section className="stats-row"><div><small>LEVEL</small><strong>{String(level).padStart(2,"0")}</strong><span className="meter"><i style={{width:`${user.progress.xp%100}%`}}/></span><R as="p" text={getTitle(level)}/></div><div><small>TOTAL XP</small><strong>{user.progress.xp}</strong><R as="p" text="学習(がくしゅう)の力(ちから)"/></div><div><R as="small" text="図鑑(ずかん)"/><strong>{galleryRate(user)}<sup>%</sup></strong><p>{user.progress.galleryIds.length} / {stages.length}</p></div></section><SectionTitle top="TODAY'S REVIEW" title="今日(きょう)の復習(ふくしゅう)" side={`${user.reviews.length}問(もん)`}/><button className="review-card" onClick={goMap}><div className="review-icon">↻</div><div><R as="strong" text="記憶(きおく)を軌道(きどう)に戻(もど)そう"/><R as="p" text="苦手(にがて)な知識(ちしき)を優先(ゆうせん)します"/></div><b>›</b></button><SectionTitle top="COLLECTION" title="新(あたら)しい発見(はっけん)" action={goLibrary}/><div className="discover">{stages.slice(0,2).map(s=><article key={s.id} className={user.progress.galleryIds.includes(s.id)?"":"locked"}><R text={s.category}/><div className="mini-celestial">{s.icon}</div><R as="strong" text={s.name}/><R as="small" text={s.subtitle}/></article>)}</div></div>}
function SectionTitle({top,title,side,action}:{top:string;title:string;side?:string;action?:()=>void}){return <div className="section-title"><div><small>{top}</small><R as="h2" text={title}/></div>{side&&<R text={side}/>} {action&&<button onClick={action}><R text="すべて見(み)る"/></button>}</div>}

function Map({user,stagesList,open}:{user:UserData;stagesList:Stage[];open:(id:string)=>void}){return <div className="map-view"><div className="map-intro"><small>GRAND VOYAGE</small><R as="h1" text="宇宙(うちゅう)への航路(こうろ)"/><R as="p" text="天体(てんたい)を巡(めぐ)り、知識(ちしき)の星(ほし)をつなごう"/><span>{user.progress.completedStageIds.length} / {stagesList.length}</span></div><div className="map-groups">{Array.from(new Set(stagesList.map(s=>s.category))).map(group=><section key={group}><R as="h2" text={group}/>{stagesList.filter(s=>s.category===group).sort((a,b)=>a.order-b.order).map(stage=>{const status=getStageStatus(stage.id,user,stagesList);const stars=user.progress.stageStars[stage.id]??0;return <button key={stage.id} className={`stage ${status}`} onClick={()=>open(stage.id)} style={{"--stage-color":stage.color} as React.CSSProperties}><div className="stage-no">{String(stage.order).padStart(2,"0")}</div><div className="celestial">{stage.icon}</div><div className="stage-copy"><small>{status==="completed"?"COMPLETE":status==="available"?"AVAILABLE":"LOCKED"}</small><R as="strong" text={stage.name}/><R text={stage.subtitle}/><span className="stage-stars">{[1,2,3].map(n=><i className={n<=stars?"on":""} key={n}>★</i>)} {user.progress.stageScores[stage.id]??0}%</span></div><div className="stage-action">{status==="completed"?"✓":status==="available"?"→":"🔒"}</div></button>})}</section>)}</div></div>}
function StageDetail({stage,status,begin}:{stage:Stage;status:string;begin:()=>void}){return <div className="stage-detail"><div className="stage-hero" style={{"--stage-color":stage.color} as React.CSSProperties}><div className="stage-planet">{stage.icon}</div><small>STAGE {String(stage.order).padStart(2,"0")}</small><R as="h1" text={stage.name}/><R as="p" text={stage.subtitle}/></div><div className="detail-status"><span><R text="学習(がくしゅう)時間(じかん)"/><b>{stage.estimatedMinutes}<R text="分(ぷん)"/></b></span><span><R text="獲得(かくとく)"/><b>+{stage.xpReward} XP</b></span><span><R text="状態(じょうたい)"/><R as="b" text={status==="completed"?"完了(かんりょう)":status==="available"?"挑戦(ちょうせん)可能(かのう)":"未解放(みかいほう)"}/></span></div><article className="glass-card"><R as="h2" text="この天体(てんたい)について"/><R as="p" text={stage.summary}/><div className="basic-data">{stage.basicData.map(v=><div key={v.label}><R text={v.label}/><R as="strong" text={v.value}/></div>)}</div></article><div className="mission-flow">{["学習(がくしゅう)","問題(もんだい)","解説(かいせつ)","テスト","図鑑(ずかん)"].map((x,i)=><span key={x}><b>{i+1}</b><R text={x}/></span>)}</div><button className="primary" disabled={status==="locked"} onClick={begin}><R text={status==="locked"?"前(まえ)のステージをクリアしよう":"学習(がくしゅう)を始(はじ)める"}/><b>→</b></button></div>}

function LessonScreen({stage,user,complete}:{stage:Stage;user:UserData;complete:()=>void}){const lesson=lessons.find(l=>l.stageId===stage.id);if(!lesson)return <ComingSoon stage={stage}/>;const read=user.progress.readLessonIds.includes(lesson.id);return <div className="lesson-view"><div className="lesson-meta"><R text={`約(やく)${stage.estimatedMinutes}分(ぷん)`}/><R text={read?"読了(どくりょう)済(ず)み":"未読(みどく)"}/></div><EducationalDiagram lesson={lesson} stage={stage}/><article className="lesson-card"><small>LESSON 01</small><R as="h1" text={lesson.title}/><R as="p" text={lesson.body}/><MediaRail/><InfoBlock icon="✦" title="重要(じゅうよう)ポイント" body={lesson.keyPoint}/><InfoBlock icon="💡" title="豆知識(まめちしき)" body={lesson.trivia}/><R as="h2" text="関連(かんれん)項目(こうもく)"/><div className="related-pills">{lesson.related.map(x=><R key={x} text={x}/>)}</div><button className="primary" onClick={complete}><R text="読了(どくりょう)して問題(もんだい)へ"/><b>→</b></button></article></div>}
function MediaRail(){return <div className="media-rail"><div><span className="media-visual illustration">◎</span><R as="small" text="AI図解(ずかい)"/></div><div><span className="media-visual photo">🌎</span><R as="small" text="実写(じっしゃ)資料(しりょう)"/></div><div><span className="media-visual compare">↔</span><R as="small" text="比較(ひかく)"/></div></div>}
function InfoBlock({icon,title,body}:{icon:string;title:string;body:string}){return <aside className="info-block"><span>{icon}</span><div><R as="strong" text={title}/><R as="p" text={body}/></div></aside>}
function ComingSoon({stage}:{stage:Stage}){return <div className="empty-state"><div>{stage.icon}</div><R as="h1" text={`${stage.name}の学習(がくしゅう)データ`}/><R as="p" text="共通(きょうつう)テンプレートへの接続(せつぞく)は完了(かんりょう)しています。前(まえ)のステージを進(すす)めると公開(こうかい)されます。"/></div>}

function QuestionScreen({question,index,total,selected,correct,submit,next,pause}:{question:Question;index:number;total:number;selected:AnswerValue|null;correct:boolean;submit:(value:AnswerValue)=>void;next:()=>void;pause:()=>void}){const[imageFailed,setImageFailed]=useState(false);return <div className="quiz-view"><div className="lesson-progress"><span><i style={{width:`${((index+1)/total)*100}%`}}/></span><b>{index+1} / {total}</b></div><button className="pause-learning" onClick={pause}>⏸ <R text="一旦(いったん)休(やす)む"/></button><div className="quiz-tag"><R text={typeLabel(question.type)}/> ・ {question.grade}<R text="級(きゅう)"/> ・ ★{question.difficulty}</div><R as="h1" text={question.prompt}/><div className="question-tags">{question.tags.map(tag=><span key={tag}>#{tag}</span>)}</div>{question.media&&<div className="question-media">{imageFailed?<div className="image-fallback" role="img" aria-label={question.media.alt}>画像を読み込めませんでした</div>:<img src={question.media.src} alt={question.media.alt} loading="lazy" decoding="async" onError={()=>setImageFailed(true)}/>}<R text={question.media.alt}/></div>}<QuestionInput key={question.id} question={question} disabled={selected!==null} onSubmit={submit}/>{selected!==null&&<div className={`feedback ${correct?"ok":"ng"}`} role="status"><span>{correct?"✦":"!"}</span><div><R as="strong" text={correct?"正解(せいかい)！":"おしい！"}/><R as="p" text={question.explanation.conclusion}/></div></div>}<button className="primary" disabled={selected===null} onClick={next}><R text="詳(くわ)しい解説(かいせつ)を見(み)る"/><b>→</b></button></div>}
function typeLabel(type:string){const x:Record<string,string>={"multiple-choice":"四択(よんたく)問題(もんだい)","true-false":"正誤(せいご)問題(もんだい)","fill-blank":"穴埋(あなう)め問題(もんだい)",ordering:"並(なら)び替(か)え問題(もんだい)",image:"画像(がぞう)問題(もんだい)",matching:"組(く)み合(あ)わせ問題(もんだい)",passage:"文章(ぶんしょう)問題(もんだい)",photo:"写真(しゃしん)問題(もんだい)",diagram:"図解(ずかい)問題(もんだい)"};return x[type]??type}
function Explanation({question,correct,next,pause}:{question:Question;correct:boolean;next:()=>void;pause:()=>void}){const e=question.explanation;return <div className="explanation-view"><button className="pause-learning" onClick={pause}>⏸ <R text="ここで一旦(いったん)休(やす)む"/></button><div className={`answer-banner ${correct?"ok":"ng"}`}><span>{correct?"✓":"!"}</span><div><small>YOUR ANSWER</small><R as="strong" text={correct?"正解(せいかい)":"復習(ふくしゅう)しよう"}/></div></div><article className="glass-card"><small>CONCLUSION</small><R as="h2" text={e.conclusion}/><div className="explain-diagram"><div className="earth small"><span/></div><div className="spin-arrow">↻</div><R text="西(にし)から東(ひがし)へ自転(じてん)"/></div><ExplainSection title="理由(りゆう)" body={e.reason}/><ExplainSection title="覚(おぼ)え方(かた)" body={e.memoryTip}/><ExplainSection title="試験(しけん)ポイント" body={e.examPoint}/><ExplainSection title="豆知識(まめちしき)" body={e.trivia}/>{e.otherChoices&&<div><R as="h3" text="ほかの選択肢(せんたくし)"/>{e.otherChoices.map(x=><R as="p" key={x} text={`・${x}`}/>)}</div>}</article><button className="related-card"><span>🌍</span><div><small>RELATED GALLERY</small><R as="strong" text="地球(ちきゅう)の図鑑(ずかん)"/></div><b>›</b></button><button className="primary" onClick={next}><R text="次(つぎ)へ進(すす)む"/><b>→</b></button></div>}
function ExplainSection({title,body}:{title:string;body:string}){return <section className="explain-section"><R as="h3" text={title}/><R as="p" text={body}/></section>}
function MiniTest({stage,finish}:{stage:Stage;finish:()=>void}){return <div className="mini-test"><div className="test-ring"><strong>4 / 4</strong><R text="学習(がくしゅう)完了(かんりょう)"/></div><small>FINAL CHECK</small><R as="h1" text="ミニテスト合格(ごうかく)！"/><R as="p" text={`${stage.name}の基本(きほん)をしっかり理解(りかい)できました。`}/><div className="test-summary"><span><R text="正答率(せいとうりつ)"/><b>100%</b></span><span><R text="学習(がくしゅう)時間(じかん)"/><b>{stage.estimatedMinutes}<R text="分(ぷん)"/></b></span></div><button className="primary" onClick={finish}><R text="ステージをクリアする"/><b>✦</b></button></div>}
function Clear({stage,level,map,library}:{stage:Stage;level:number;map:()=>void;library:()=>void}){return <div className="clear-view"><div className="confetti">✦ <i>✧</i> ✦</div><div className="clear-planet">{stage.icon}</div><small>STAGE COMPLETE</small><R as="h1" text={`${stage.name}クリア！`}/><R as="p" text="新(あたら)しい航路(こうろ)が開(ひら)きました。"/><div className="reward-card"><span><R text="獲得(かくとく)XP"/><b>+{stage.xpReward}</b></span><span><R text="現在(げんざい)レベル"/><b>{level}</b></span></div><button className="gallery-unlock" onClick={library}><span>▤</span><div><small>GALLERY UPDATED</small><R as="strong" text={`${stage.name}を図鑑(ずかん)に登録(とうろく)`}/></div><b>›</b></button><button className="primary" onClick={map}><R text="宇宙(うちゅう)マップへ"/><b>→</b></button></div>}

function Library({user,open,toggleFavorite}:{user:UserData;open:(id:string)=>void;toggleFavorite:(id:string)=>void}){const[c,setC]=useState("すべて");const[query,setQuery]=useState("");const cats=["すべて","惑星","衛星","恒星","銀河","探査機","人物","星座","現象","宇宙開発"];const shown=gallery.filter(g=>(c==="すべて"||g.category===c)&&(!query||`${g.title}${g.subtitle}${g.tags.join(" ")}`.includes(query)));return <div className="library-view"><div className="library-head"><small>MY COSMOS</small><R as="h1" text="宇宙(うちゅう)図鑑(ずかん)"/><R as="p" text="発見(はっけん)した天体(てんたい)と知識(ちしき)のコレクション"/><div><strong>{user.progress.galleryIds.length}</strong><span>/ {gallery.length}</span></div></div><label className="gallery-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="名前・タグで検索"/></label><div className="category-pills">{cats.map(x=><button key={x} className={c===x?"active":""} onClick={()=>setC(x)}>{x}</button>)}</div><div className="library-grid">{shown.map(g=>{const s=stages.find(x=>x.id===g.stageId);const on=user.progress.galleryIds.includes(g.id);const favorite=user.progress.favoriteGalleryIds.includes(g.id);return <button key={g.id} className={on?"":"locked"} onClick={()=>g.stageId&&open(g.stageId)}><div>{g.icon}{!on&&<span>🔒</span>}</div><small>{g.category}</small><R as="strong" text={on?g.title:"未発見(みはっけん)"}/><i style={{background:s?.color??"#79ddff"}}/><span className={`favorite ${favorite?"on":""}`} onClick={e=>{e.stopPropagation();toggleFavorite(g.id)}}>★</span></button>})}</div>{!shown.length&&<div className="empty-mini"><R text="条件(じょうけん)に合(あ)う項目(こうもく)はありません"/></div>}</div>}
function GalleryDetail({stage,unlocked,learn}:{stage:Stage;unlocked:boolean;learn:()=>void}){if(!unlocked)return <div className="empty-state"><div>🔒</div><R as="h1" text="まだ発見(はっけん)されていません"/><R as="p" text={`${stage.name}のステージをクリアすると、詳(くわ)しい情報(じょうほう)が開(ひら)きます。`}/><button className="primary" onClick={learn}><R text="ステージを見(み)る"/><b>→</b></button></div>;return <div className="gallery-detail"><div className="gallery-cover" style={{"--stage-color":stage.color} as React.CSSProperties}><div>{stage.icon}</div><R as="small" text={stage.category}/><R as="h1" text={stage.name}/><R as="p" text={stage.subtitle}/></div><article className="glass-card"><R as="h2" text="基本(きほん)データ"/><div className="basic-data">{stage.basicData.map(x=><div key={x.label}><R text={x.label}/><R as="strong" text={x.value}/></div>)}</div><R as="h2" text="解説(かいせつ)"/><R as="p" text={stage.summary}/><MediaRail/><InfoBlock icon="💡" title="宇宙(うちゅう)の雑学(ざつがく)" body="観測(かんそく)する波長(はちょう)を変(か)えると、同(おな)じ天体(てんたい)でも違(ちが)う姿(すがた)が見(み)えます。"/><R as="h2" text="学習(がくしゅう)状況(じょうきょう)"/><div className="mastery"><span><i style={{width:"100%"}}/></span><b>100%</b></div></article></div>}
function Profile({user}:{user:UserData}){const level=getLevel(user.progress.xp);const earned=achievementData.filter(a=>user.achievements.includes(a.id));const accuracy=user.statistics.answered?Math.round(user.statistics.correct/user.statistics.answered*100):0;const recent=user.questionHistory.slice(-3).reverse();const weak=Object.entries(user.questionHistory.filter(x=>!x.correct).reduce<Record<string,number>>((a,h)=>{const q=questions.find(x=>x.id===h.questionId);if(q)a[q.category]=(a[q.category]??0)+1;return a},{})).sort((a,b)=>b[1]-a[1]).slice(0,3);return <div className="profile-view"><div className="avatar">👨‍🚀</div><small>SPACE CADET</small><R as="h1" text={`${user.player.name}船長(せんちょう)`}/><R as="p" text={getTitle(level)}/><div className="rank-card"><div><R text="宇宙船(うちゅうせん)ランク"/><R as="strong" text={getShipRank(level)}/></div><span>LV.{level}</span></div><div className="profile-stats six"><div><strong>{user.statistics.answered}</strong><R text="総問題数(そうもんだいすう)"/></div><div><strong>{accuracy}%</strong><R text="正答率(せいとうりつ)"/></div><div><strong>{Math.round(user.statistics.learningSeconds/60)}</strong><R text="学習(がくしゅう)分数(ふんすう)"/></div><div><strong>{galleryRate(user)}%</strong><R text="図鑑率(ずかんりつ)"/></div><div><strong>{user.statistics.streak}</strong><R text="連続(れんぞく)日数(にっすう)"/></div><div><strong>{user.progress.completedStageIds.length}</strong><R text="完了(かんりょう)"/></div></div><R as="h2" text="苦手(にがて)分野(ぶんや)"/><div className="insight-list">{weak.length?weak.map(([name,count])=><span key={name}>{name}<b>{count}<R text="回(かい)"/></b></span>):<R text="まだ苦手(にがて)な分野(ぶんや)はありません"/>}</div><R as="h2" text="最近(さいきん)の学習(がくしゅう)"/><div className="insight-list">{recent.length?recent.map((h,i)=><span key={`${h.questionId}-${i}`}><R text={questions.find(q=>q.id===h.questionId)?.prompt??h.questionId}/><b>{h.correct?"✓":"↻"}</b></span>):<R text="問題(もんだい)に答(こた)えると記録(きろく)されます"/>}</div><R as="h2" text="実績(じっせき)"/><div className="achievement-list">{achievementData.map(a=>{const on=earned.includes(a);return <div key={a.id} className={on?"":"locked"}><span>{on?a.icon:"🔒"}</span><div><R as="strong" text={a.title}/><R as="small" text={a.description}/></div></div>})}</div></div>}
function Settings({user,update}:{user:UserData;update:<K extends keyof AppSettings>(key:K,value:AppSettings[K])=>void}){const value=user.settings;return <div className="settings-view"><R as="h1" text="学習(がくしゅう)環境(かんきょう)"/><R as="p" text="自分(じぶん)に合(あ)わせて体験(たいけん)を調整(ちょうせい)できます。"/><SettingsToggle label="BGM" value={value.bgm} set={v=>update("bgm",v)}/><SettingsToggle label="効果音(こうかおん)" value={value.se} set={v=>update("se",v)}/><SettingsToggle label="振動(しんどう)" value={value.vibration} set={v=>update("vibration",v)}/><SettingsToggle label="省(しょう)アニメーション" value={value.reducedMotion} set={v=>update("reducedMotion",v)}/><SettingsToggle label="復習(ふくしゅう)通知(つうち)" value={value.notifications} set={v=>update("notifications",v)}/><div className="setting-group"><R as="strong" text="文字(もじ)サイズ"/><div className="segmented">{(["small","medium","large"] as const).map((x,i)=><button className={value.fontScale===x?"active":""} key={x} onClick={()=>update("fontScale",x)}><R text={["小(しょう)","標準(ひょうじゅん)","大(だい)"][i]}/></button>)}</div></div><div className="storage-note"><span>✓</span><R as="p" text="XP・図鑑・宇宙船・基地・実績・コイン・設定は、アップデート後もこの端末に安全に保存されます。"/></div><PwaDiagnostics saveVersion={user.saveVersion}/></div>}
function SettingsToggle({label,value,set}:{label:string;value:boolean;set:(v:boolean)=>void}){return <button className="toggle-row" onClick={()=>set(!value)}><R text={label}/><span className={value?"on":""}><i/></span></button>}
