"use client";

import { RubyText as R } from "@/components/RubyText";
import type { GalleryItem, Mission, Stage, Topic, UserData } from "@/domain/models";
import { getLevel, getShipRank, getStageStatus } from "@/lib/progression";

type AdventureProps = { user:UserData; stages:Stage[]; topics:Topic[]; gallery:GalleryItem[]; missions:Mission[]; openMap:()=>void; openStage:(id:string)=>void };

export function AdventureHome({user,stages,topics,gallery,missions,openMap,openStage}:AdventureProps){
 const level=getLevel(user.progress.xp); const current=stages.find(s=>s.id===user.progress.currentStageId)??stages[0]; const next=stages.find(s=>getStageStatus(s.id,user,stages)==="available")??current;
 const discoveries=gallery.filter(x=>user.progress.galleryIds.includes(x.id)).slice(-4).reverse(); const discoveredTopics=topics.filter(x=>user.topicProgress[x.id]).length;
 return <section className="adventure-home" aria-label="宇宙冒険モード">
  <div className="adventure-kicker"><span>ADVENTURE MODE</span><R text="宇宙(うちゅう)を旅(たび)して、発見(はっけん)を集(あつ)めよう"/></div>
  <article className="ship-hangar"><div className="ship-space" aria-hidden="true"><i/><i/><i/><div className="spaceship"><span/><b/><em/></div></div><div className="ship-copy"><small>MY SPACECRAFT</small><R as="h2" text="探査船(たんさせん) コスモ・ゼロ"/><div className="ship-meta"><span>LV.{level}</span><R text={getShipRank(level)}/></div><R as="p" text="宇宙船(うちゅうせん)の色(いろ)や機体(きたい)は、これから集(あつ)められるようになります。"/><div className="ship-colors" role="img" aria-label="宇宙船カラー"><i className="selected"/><i/><i/><i/></div></div></article>
  <article className="flight-card"><div><small>CURRENT LOCATION</small><R as="strong" text={current.name}/><R text="現在地(げんざいち)"/></div><span className="flight-line"><i>🚀</i></span><div><small>NEXT DESTINATION</small><R as="strong" text={next.name}/><R text="次(つぎ)の目的地(もくてきち)"/></div><button onClick={openMap}><R text="銀河(ぎんが)マップを開(ひら)く"/> <b>→</b></button></article>
  <div className="adventure-grid"><article className="mission-board"><header><div><small>MISSION BOARD</small><R as="h2" text="今日(きょう)の調査任務(ちょうさにんむ)"/></div><span>{missions.length}</span></header>{missions.slice(0,3).map((m,i)=><div className="mission-slip" key={m.id}><b>{String(i+1).padStart(2,"0")}</b><div><R as="strong" text={m.title}/><R as="small" text={m.description}/></div><span>+{m.xpReward} XP</span></div>)}</article><article className="discovery-summary"><small>DISCOVERY LOG</small><R as="h2" text="発見記録(はっけんきろく)"/><strong>{discoveries.length}<small> CARDS</small></strong><R as="p" text={`学習(がくしゅう)したTopic：${discoveredTopics}件(けん)`}/></article></div>
  <div className="discovery-head"><div><small>RECENT DISCOVERIES</small><R as="h2" text="最近(さいきん)の発見(はっけん)"/></div><R text="カードを選(えら)んで再調査(さいちょうさ)"/></div>
  <div className="discovery-album">{(discoveries.length?discoveries:gallery.slice(0,4)).map((item,i)=>{const unlocked=user.progress.galleryIds.includes(item.id);return <button key={item.id} className={`discovery-card ${unlocked?"unlocked":"unknown"} ${i===0&&unlocked?"rare":""}`} onClick={()=>item.stageId&&openStage(item.stageId)} disabled={!item.stageId}><span className="card-rarity">{unlocked?(i===0?"RARE":"FOUND"):"UNKNOWN"}</span><b className="card-icon">{unlocked?item.icon:"?"}</b><R as="strong" text={unlocked?item.title:"未発見(みはっけん)"}/><R as="small" text={unlocked?item.subtitle:"冒険(ぼうけん)を進(すす)めよう"}/></button>})}</div>
 </section>
}

export function GalaxyMap({user,stages,open}:{user:UserData;stages:Stage[];open:(id:string)=>void}){return <section className="adventure-galaxy"><header><small>GALAXY EXPLORATION MAP</small><R as="h1" text="コスモ航宙図(こうちゅうず)"/><R as="p" text="天体(てんたい)を調査(ちょうさ)すると航路(こうろ)が光(ひか)り、次(つぎ)の目的地(もくてきち)が現(あらわ)れます。"/></header><div className="galaxy-legend"><span className="done">● <R text="調査完了(ちょうさかんりょう)"/></span><span className="now">● <R text="調査可能(ちょうさかのう)"/></span><span>● <R text="未開放(みかいほう)"/></span></div><div className="galaxy-field">{stages.slice().sort((a,b)=>a.order-b.order).map((stage,index)=>{const status=getStageStatus(stage.id,user,stages);const stars=user.progress.stageStars[stage.id]??0;const x=[18,55,77,35,68,22][index%6];return <div className={`galaxy-stop ${status}`} key={stage.id} style={{"--node-x":`${x}%`,"--node-color":stage.color,"--node-top":`${30+index*90}px`} as React.CSSProperties}>{index>0&&<i className="route"/>}<button onClick={()=>status!=="locked"&&open(stage.id)} disabled={status==="locked"}><span className="node-orbit"><b>{status==="locked"?"🔒":stage.icon}</b></span>{status==="available"&&<em className="ship-marker">🚀</em>}<small>{status==="completed"?"EXPLORED":status==="available"?"NEXT MISSION":"LOCKED"}</small><R as="strong" text={stage.name}/><span className="map-stars">{"★".repeat(stars)}{"☆".repeat(3-stars)}</span></button></div>})}</div></section>}
