"use client";
/* eslint-disable @typescript-eslint/no-unused-vars */
import { useState, type CSSProperties } from "react";
import { artifacts, ships, shopItems } from "@/data/game-system";
import type { GalleryItem, UserData } from "@/domain/models";
import { baseLevel, baseName, dailyProgress, levelFromXp, playerTitle, shipClass, weeklyProgress } from "@/lib/game-engine";

type Tab="base"|"fleet"|"mission"|"shop"|"museum";
const upgrades=[
  {level:1,name:"ブースター翼",price:200,detail:"左右の安定翼を追加"},
  {level:2,name:"ツインエンジン",price:450,detail:"推進炎とエンジンを強化"},
  {level:3,name:"探査センサー",price:800,detail:"船首レーダーを装備"},
  {level:4,name:"プラズマシールド",price:1300,detail:"船体の周囲に防護リングを展開"},
  {level:5,name:"コスモ・コア",price:2000,detail:"最終形態の発光コアを搭載"},
] as const;

function CssShip({level,color,engine,compact=false}:{level:number;color:string;engine:string;compact?:boolean}){return <div className={`css-ship upgrade-${level} ${compact?"compact":""}`} style={{"--ship":color} as CSSProperties} role="img" aria-label={`宇宙船 アップグレードレベル${level}`}><i className="ship-shield"/><i className="ship-trail left"/><i className="ship-trail right"/><div className="ship-wing left"/><div className="ship-wing right"/><div className="ship-hull"><i className="ship-sensor"/><i className="ship-cockpit"/><i className="ship-core"/><i className="ship-stripe"/></div><i className={`ship-engine left ${engine}`}/><i className={`ship-engine right ${engine}`}/></div>}

export function SpaceRpg({user,gallery:_gallery,onUser}:{user:UserData;gallery:GalleryItem[];onUser:(u:UserData)=>void}){
  const[tab,setTab]=useState<Tab>("base");const lv=levelFromXp(user.progress.xp),base=baseLevel(user),selected=ships.find(s=>s.id===user.game.shipId)??ships[0],found=artifacts.filter(a=>user.game.artifactIds.includes(a.id));
  const upgradeLevel=user.game.shipUpgradeLevel??0;const nextUpgrade=upgrades[upgradeLevel];
  const update=(g:Partial<UserData["game"]>)=>onUser({...user,game:{...user.game,...g}});
  const claim=(id:string,reward:number,weekly=false)=>{const key=weekly?"claimedWeeklyIds":"claimedDailyIds";if(user.game[key].includes(id))return;onUser({...user,progress:{...user.progress,xp:user.progress.xp+reward},game:{...user.game,coins:user.game.coins+Math.floor(reward/2),[key]:[...user.game[key],id],lastReward:{kind:"xp",label:`MISSION CLEAR +${reward} XP`}}})};
  const buy=(i:typeof shopItems[number])=>{if(user.game.coins<i.price||user.game.ownedItemIds.includes(i.id))return;update({coins:user.game.coins-i.price,ownedItemIds:[...user.game.ownedItemIds,i.id],...(i.kind==="COLOR"?{shipColor:i.value}:i.kind==="ENGINE"?{engineId:i.value}:{suitId:i.value})})};
  const upgrade=()=>{if(!nextUpgrade||user.game.coins<nextUpgrade.price)return;update({coins:user.game.coins-nextUpgrade.price,shipUpgradeLevel:nextUpgrade.level,lastReward:{kind:"discovery",label:`宇宙船をLV.${nextUpgrade.level}へアップグレード`}})};
  return <section className="space-rpg"><header className="rpg-command"><div><small>CIVILIZATION COMMAND</small><h2>学ぶほど、宇宙文明は進化する</h2></div><div><span>LV.{lv}</span><b>◈ {user.game.coins}</b></div></header><nav className="rpg-tabs">{([['base','基地'],['fleet','艦隊'],['mission','任務'],['shop','ショップ'],['museum','博物館']] as const).map(([id,label])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav>
  {tab==="base"&&<><article className={`space-base base-${base}`}><div className="base-sky"><i/><i/><i/></div><div className="base-planet"/><div className="base-buildings">{Array.from({length:Math.min(8,base+1)},(_,i)=><span key={i} style={{"--b":i} as CSSProperties}/>)}</div><div className="base-people"><i/><i/><b/></div><div className="base-ship"><CssShip compact level={upgradeLevel} color={user.game.shipColor} engine={user.game.engineId}/></div><div className="base-copy"><small>BASE LEVEL {base}/10</small><strong>{baseName(user)}</strong><span>{playerTitle(lv)} · {shipClass(lv)}</span></div></article><div className="civilization-stats">{[[Object.keys(user.topicProgress).length,"調査Topic"],[user.progress.galleryIds.length,"図鑑登録"],[found.length,"遺物収集"],[user.achievements.length,"トロフィー"]].map(([n,l])=><div key={l}><b>{n}</b><span>{l}</span></div>)}</div></>}
  {tab==="fleet"&&<><div className="fleet-preview"><CssShip level={upgradeLevel} color={user.game.shipColor} engine={user.game.engineId}/><div><small>ACTIVE SHIP · UPGRADE {upgradeLevel}/5</small><strong>{selected.name}</strong><span>{nextUpgrade?`次: ${nextUpgrade.name}`:"MAX UPGRADE"}</span></div></div><article className="upgrade-console"><div><small>SHIP UPGRADE</small><strong>{nextUpgrade?.name??"コスモ・コア完成"}</strong><span>{nextUpgrade?.detail??"すべての拡張パーツを搭載済みです"}</span></div><button disabled={!nextUpgrade||user.game.coins<(nextUpgrade?.price??0)} onClick={upgrade}>{nextUpgrade?`◈ ${nextUpgrade.price} で購入`:"MAX"}</button></article><div className="upgrade-dots">{[1,2,3,4,5].map(n=><i className={n<=upgradeLevel?"on":""} key={n}/>)}</div><div className="ship-palette">{["#79ddff","#64f1d1","#ffb44f","#db78ff","#f4f7ff"].map(c=><button key={c} style={{background:c}} className={user.game.shipColor===c?"active":""} onClick={()=>update({shipColor:c})} aria-label={`船体色 ${c}`}/>)}</div><div className="fleet-grid">{ships.map(s=>{const open=lv>=s.unlock;return <button key={s.id} disabled={!open} className={user.game.shipId===s.id?"selected":""} onClick={()=>update({shipId:s.id,unlockedShipIds:Array.from(new Set([...user.game.unlockedShipIds,s.id]))})}><b>{open?s.icon:"🔒"}</b><strong>{s.name}</strong><small>{open?s.style:`LV.${s.unlock}で解放`}</small></button>})}</div></>}
  {tab==="mission"&&<><MissionList title="DAILY MISSIONS" items={dailyProgress(user)} claimed={user.game.claimedDailyIds} claim={(id,r)=>claim(id,r)}/><MissionList title="WEEKLY OPERATIONS" items={weeklyProgress(user)} claimed={user.game.claimedWeeklyIds} claim={(id,r)=>claim(id,r,true)}/></>}
  {tab==="shop"&&<><div className="shop-head"><div><small>NO REAL MONEY</small><strong>コスモ・コインショップ</strong></div><b>◈ {user.game.coins}</b></div><div className="shop-grid">{shopItems.map(i=>{const owned=user.game.ownedItemIds.includes(i.id);return <button key={i.id} disabled={owned||user.game.coins<i.price} onClick={()=>buy(i)}><span>{i.kind}</span><b>{i.kind==="COLOR"?"◉":i.kind==="ENGINE"?"⚡":"♙"}</b><strong>{i.name}</strong><em>{owned?"OWNED":`◈ ${i.price}`}</em></button>})}</div></>}
  {tab==="museum"&&<><div className="museum-hall"><header><small>COSMO MUSEUM</small><strong>{found.length} / {artifacts.length} ARTIFACTS</strong></header><div className="museum-grid">{(found.length?found:artifacts.slice(0,8)).slice(0,24).map(a=><article className={user.game.artifactIds.includes(a.id)?"":"unknown"} key={a.id}><span>{user.game.artifactIds.includes(a.id)?a.icon:"?"}</span><strong>{user.game.artifactIds.includes(a.id)?a.name:"未発見"}</strong><small>{"★".repeat(a.rarity)}</small></article>)}</div></div></>}
  </section>;
}
function MissionList({title,items,claimed,claim}:{title:string;items:{id:string;label:string;now:number;target:number;reward:number}[];claimed:string[];claim:(id:string,r:number)=>void}){return <article className="rpg-missions"><h3>{title}</h3>{items.map(m=>{const done=m.now>=m.target,got=claimed.includes(m.id);return <div key={m.id}><span><i style={{width:`${Math.min(100,m.now/m.target*100)}%`}}/></span><div><strong>{m.label}</strong><small>{m.now}/{m.target} · +{m.reward} XP</small></div><button disabled={!done||got} onClick={()=>claim(m.id,m.reward)}>{got?"取得済":done?"取得":"進行中"}</button></div>})}</article>}
