"use client";
import { useState } from "react";
import { artifacts, ships, shopItems } from "@/data/game-system";
import type { GalleryItem, UserData } from "@/domain/models";
import { baseLevel, baseName, dailyProgress, levelFromXp, playerTitle, shipClass, weeklyProgress } from "@/lib/game-engine";
type Tab="base"|"fleet"|"mission"|"shop"|"museum";
export function SpaceRpg({user,gallery,onUser}:{user:UserData;gallery:GalleryItem[];onUser:(u:UserData)=>void}){const[tab,setTab]=useState<Tab>("base");const lv=levelFromXp(user.progress.xp),base=baseLevel(user),selected=ships.find(s=>s.id===user.game.shipId)??ships[0],found=artifacts.filter(a=>user.game.artifactIds.includes(a.id));const update=(g:Partial<UserData["game"]>)=>onUser({...user,game:{...user.game,...g}});const claim=(id:string,reward:number,weekly=false)=>{const key=weekly?"claimedWeeklyIds":"claimedDailyIds";if(user.game[key].includes(id))return;onUser({...user,progress:{...user.progress,xp:user.progress.xp+reward},game:{...user.game,coins:user.game.coins+Math.floor(reward/2),[key]:[...user.game[key],id],lastReward:{kind:"xp",label:`MISSION CLEAR +${reward} XP`}}})};const buy=(i:typeof shopItems[number])=>{if(user.game.coins<i.price||user.game.ownedItemIds.includes(i.id))return;update({coins:user.game.coins-i.price,ownedItemIds:[...user.game.ownedItemIds,i.id],...(i.kind==="COLOR"?{shipColor:i.value}:i.kind==="ENGINE"?{engineId:i.value}:{suitId:i.value})})};return <section className="space-rpg"><header className="rpg-command"><div><small>CIVILIZATION COMMAND</small><h2>学ぶほど、宇宙文明は進化する</h2></div><div><span>LV.{lv}</span><b>◈ {user.game.coins}</b></div></header><nav className="rpg-tabs">{([['base','基地'],['fleet','艦隊'],['mission','任務'],['shop','ショップ'],['museum','博物館']] as const).map(([id,label])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav>
{tab==="base"&&<><article className={`space-base base-${base}`}><div className="base-sky"><i/><i/><i/></div><div className="base-planet"/><div className="base-buildings">{Array.from({length:Math.min(8,base+1)},(_,i)=><span key={i} style={{"--b":i} as React.CSSProperties}/>)}</div><div className="base-people"><i/><i/><b/></div><div className="base-ship" style={{"--ship":user.game.shipColor} as React.CSSProperties}><span>{selected.icon}</span><i className={user.game.engineId}/></div><div className="base-copy"><small>BASE LEVEL {base}/10</small><strong>{baseName(user)}</strong><span>{playerTitle(lv)} · {shipClass(lv)}</span></div></article><div className="civilization-stats">{[[Object.keys(user.topicProgress).length,"調査Topic"],[user.progress.galleryIds.length,"図鑑登録"],[found.length,"遺物収集"],[user.achievements.length,"トロフィー"]].map(([n,l])=><div key={l}><b>{n}</b><span>{l}</span></div>)}</div><article className="space-news"><span>✦</span><div><small>TODAY&apos;S SPACE NEWS</small><p>{gallery[(new Date().getDate()+gallery.length)%Math.max(1,gallery.length)]?.description??"宇宙には、まだ名前のない発見が待っています。"}</p></div></article></>}
{tab==="fleet"&&<><div className="fleet-preview" style={{"--ship":user.game.shipColor} as React.CSSProperties}><div className="fleet-ship"><span>{selected.icon}</span><i className={user.game.engineId}/></div><div><small>ACTIVE SHIP · LV.{lv}</small><strong>{selected.name}</strong><span>{shipClass(lv)}</span></div></div><div className="ship-palette">{["#79ddff","#64f1d1","#ffb44f","#db78ff","#f4f7ff"].map(c=><button key={c} style={{background:c}} className={user.game.shipColor===c?"active":""} onClick={()=>update({shipColor:c})} aria-label={`船体色 ${c}`}/>)}</div><div className="fleet-grid">{ships.map(s=>{const open=lv>=s.unlock;return <button key={s.id} disabled={!open} className={user.game.shipId===s.id?"selected":""} onClick={()=>update({shipId:s.id,unlockedShipIds:Array.from(new Set([...user.game.unlockedShipIds,s.id]))})}><b>{open?s.icon:"🔒"}</b><strong>{s.name}</strong><small>{open?s.style:`LV.${s.unlock}で解放`}</small></button>})}</div></>}
{tab==="mission"&&<><MissionList title="DAILY MISSIONS" items={dailyProgress(user)} claimed={user.game.claimedDailyIds} claim={(id,r)=>claim(id,r)}/><MissionList title="WEEKLY OPERATIONS" items={weeklyProgress(user)} claimed={user.game.claimedWeeklyIds} claim={(id,r)=>claim(id,r,true)}/><div className="login-bonus"><small>7 DAY LOGIN BONUS</small>{[50,100,150,200,300,400,700].map((x,i)=><span className={i<user.game.loginDays%7?"done":""} key={i}><b>{i+1}</b><em>+{x}</em></span>)}</div></>}
{tab==="shop"&&<><div className="shop-head"><div><small>NO REAL MONEY</small><strong>コスモ・コインショップ</strong></div><b>◈ {user.game.coins}</b></div><div className="shop-grid">{shopItems.map(i=>{const owned=user.game.ownedItemIds.includes(i.id);return <button key={i.id} disabled={owned||user.game.coins<i.price} onClick={()=>buy(i)}><span>{i.kind}</span><b>{i.kind==="COLOR"?"●":i.kind==="ENGINE"?"≋":"♙"}</b><strong>{i.name}</strong><em>{owned?"OWNED":`◈ ${i.price}`}</em></button>})}</div></>}
{tab==="museum"&&<><div className="museum-hall"><header><small>COSMO MUSEUM</small><strong>{found.length} / {artifacts.length} ARTIFACTS</strong></header><div className="museum-grid">{(found.length?found:artifacts.slice(0,8)).slice(0,24).map(a=><article className={user.game.artifactIds.includes(a.id)?"":"unknown"} key={a.id}><span>{user.game.artifactIds.includes(a.id)?a.icon:"?"}</span><strong>{user.game.artifactIds.includes(a.id)?a.name:"未発見"}</strong><small>{"★".repeat(a.rarity)}</small></article>)}</div></div><div className="collection-rate"><span><i style={{width:`${Math.round(user.progress.galleryIds.length/Math.max(1,gallery.length)*100)}%`}}/></span><b>図鑑完成率 {Math.round(user.progress.galleryIds.length/Math.max(1,gallery.length)*100)}%</b></div></>}</section>}
function MissionList({title,items,claimed,claim}:{title:string;items:{id:string;label:string;now:number;target:number;reward:number}[];claimed:string[];claim:(id:string,r:number)=>void}){return <article className="rpg-missions"><h3>{title}</h3>{items.map(m=>{const done=m.now>=m.target,got=claimed.includes(m.id);return <div key={m.id}><span className={done?"done":""}><i style={{width:`${Math.min(100,m.now/m.target*100)}%`}}/></span><div><strong>{m.label}</strong><small>{m.now}/{m.target} · +{m.reward} XP</small></div><button disabled={!done||got} onClick={()=>claim(m.id,m.reward)}>{got?"受取済":done?"受取":"進行中"}</button></div>})}</article>}
